zavrsni/accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
    path('profile/', views.dashboard, name="profile_login"),
    path('profile/<int:user_id>', views.profile, name="profile"),
    path('profile/rate/', views.rate, name="create-rate"),
    path("signup/", views.signup_view, name="signup"),
    path("finishup/", views.finishup, name="finishup"),
    path("dashboard/<int:travel_id>/edit", views.available, name='available'),
    path("dashboard/<int:trip_id>/edit2", views.edit2, name='edit2'),
    path("dashboard/<int:travel_id>/delete", views.delete, name='delete'),
    path('messages/', views.messages, name="messages"),
    path('messages/<int:user_id>', views.chat, name="chat"),
    path('message/<int:user_id>', views.create_message, name="create-message"),
]

zavrsni/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from travels.views import home, list, create_trip, create_travel

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('travels/', include('travels.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('list/', list, name="list"),
    path('create_trip/<int:travel_id>/', create_trip, name='create_trip'),
    path('list/create/', create_travel, name="create-travel")
    
]

zavrsni/travels/urls.py
from django.urls import path
from travels.views import list

app_name="travels"
urlpatterns = [
    
]

zavrsni/travels/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import DateTimeField

# Create your models here.
class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    organization = models.BooleanField()

    def __str__(self):
        return f"{self.id} - {self.name}"

class Travels(models.Model):

    user=models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    desc = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    date = models.DateField(auto_now=False, auto_now_add=False) 
    photo = models.CharField(max_length=100)
    status = models.CharField(max_length=100, default="available")


    def __str__(self):
        return f"{self.user.account.name} - {self.title}"

class Messages(models.Model):

    sender_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
    reciever_id = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reciever')
    text= models.TextField()
    sent_at = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return f"{self.sender_id.account.name} -> {self.reciever_id.account.name} - {self.text[:20]}"

    

class Trips(models.Model):

    travel=models.ForeignKey(Travels, on_delete=models.CASCADE)
    traveler = models.ForeignKey(User, on_delete=models.CASCADE)    
    rating=models.IntegerField(default=0)
    def __str__(self):
        return f"{self.travel.title} - {self.traveler.account.name}"

zavrsni/travels/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.utils import timezone
from django.urls import reverse


from .models import Account, Travels, Messages, User, Trips
# Create your views here.
def home(request):
    formatted_time = timezone.now().strftime("%H:%M:%S.%f")
    context = {
        'current_time': formatted_time,
    }
    return render(request,  'travels/home.html', context)

def list(request):
    travels = Travels.objects.filter(status="available")
    context={
        'travels': travels,
    }
    return render(request, 'travels/list.html', context)


def create_trip(request, travel_id):

    if request.method == "POST" and request.user.is_authenticated:
        # Get the travel instance
        travel = get_object_or_404(Travels, id=travel_id)
        
        # Create a new trip
        trip = Trips.objects.create(
            travel=travel,
            traveler=request.user
        )
        
        # Update the status of the travel
        travel.status = "In Progress"
        travel.save()
        trip.save()
        
    return redirect(reverse('list'))  


def create_travel(request):

    if request.method == "POST" and request.user.is_authenticated:
        
        title=request.POST['title']
        desc=request.POST['desc']
        location = request.POST['location']
        date = request.POST.get('date', '')
        url=request.POST['url']

        if not title and not desc and not location and not date and not url:
            return render(request, 'travels/create_travel.html', context = {})
        
        if date=="":
         return render(request, 'travels/create_travel.html', context = {})
        


        travel=Travels(
            user=request.user,
            title = title,
            desc = desc,
            location = location,
            date = date,
            photo = url
        )
        travel.save()

        return redirect(reverse('list'))
    context = {}
    return render(request, 'travels/create_travel.html', context)

zavrsni/travels/templates/travels/base.html
{% load static %}
<html>
  <head>
    <title>
        Traveling app | 
        {% block title %}{% endblock %}
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"></script>
    
    <link rel="stylesheet" href="{% static 'travels/css/travels.css' %}">
  </head>

  <body>
    <div class="page-header">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'home' %}">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'list'%}">All travels</a>
            </li>
            {% if request.user.account.organization %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'create-travel' %}">Add new travel</a>
              </li>
            {% endif %}
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:dashboard' %}">{{user.account.name}}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:profile' user.id %}">My profile</a>
            </li>

              <li class="nav-item">
                <form action="{% url 'logout' %}" method="post">
                  {% csrf_token %}
                  <button class="btn btn-link nav-link" type="submit">Logout</button>
                </form>
              </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup' %}">SignUp</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>
    <div class="content container">
      <div class="row">
        <div class="col-md-12">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </body>
</html>

zavrsni/travels/templates/travels/create_travel.html
{% extends 'travels/base.html' %}

{% block title %}
Add travel
{% endblock %}

{% block content %}
        <h1>Add new travel</h1>
        <form method="post" action="{% url 'create-travel' %}">
            {% csrf_token %}
            <label>Title</label>
            <input type="text" name="title">
            <br>

            <label>Description</label>
            <input type="text" name="desc">
            <br>
            
            <label>Location</label>
            <input type="text" name="location">
            <br>

            <label>Date</label>
            <input type="date" name="date">
            <br>
            
            <label>Photo url</label>
            <input type="text" name="url">
            <br>
            
            <input type="submit" value="Add travel">
        </form>


{% endblock content %}

zavrsni/travels/templates/travels/home.html
{% extends 'travels/base.html' %}

{% block title %}
Početna
{% endblock %}

{% block content %}
    <h1>Welcome to Traveling app</h1>
    <p>Current time: {{ current_time }}</p>
    <br>
    <p>Click here to see all available travels <a href="{% url 'list' %}">List</a></p>
{% endblock content %}

zavrsni/travels/templates/travels/list.html
{% extends 'travels/base.html' %}

{% block title %}
Travel list
{% endblock %}

{% block content %}
<div class="content container">
    <div class="row">
        <div class="col-md-12">
            
            {% if travels  %}
                {% else %}
                <p>None at this time</p>
            {% endif %}
                
            {% for travel in travels  %}
            <div class="travel">
                <h3>{{travel.title}}</h3>
                <p><strong>Organization: </strong><a href="{% url 'accounts:profile' travel.user.id%}">{{travel.user.account.name}}</a>
                    <a class="btn btn-primary" href="{% url 'accounts:chat' travel.user.id%}">Message</a>
                </p>
                <img src="{{travel.photo}}" style="width: 300px;">
                <p>{{travel.desc}}</p>
                <p><strong>City:</strong>  {{travel.location}}</p>
                <p><strong>Date of travel:</strong> {{travel.date}}</p>
                <p><strong>Status: </strong>{{travel.status}}</p>
                {% if request.user.is_authenticated %}
                {% if not user.account.organization  %}
                <form method="post" action="{% url 'create_trip' travel.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Join Trip</button>
                </form>
                {% endif %} {# for is organization #}
                {% else %}
                <a href="{% url 'login' %}">Login to join Trip</a>
                {% endif %}{# for is auth #}
                
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

zavrsni/travels/templates/travels/pd.html
{% extends 'images/base.html' %}

{% block title %}
Profile
{% endblock %}

{% block content %}
    <p>{{ user.username}}</p>
    <p>{{ user.first_name }} {{ user.last_name}}</p>
    <p>{{ user.email}}</p>
            
    <h1>My images</h1>
            {% for image in images %}
                <h2>
                    <a href="{% url 'detail' image.id %}">
                        {{ image.title }}
                    </a>
                </h2>
                <img src="{{ image.url }}" style="width: 300px;"/>
            {% endfor %}

    <h1>My comments</h1>
        {% for comment in comments %}
        <h2>
            
                {{ comment.text }}
            
        </h2>
        
        {% endfor %}

    <h1>My likes</h1>
        {% for like in likes %}
            <p>
                <img src="{{ like.image.url}}" style="width: 300px;"/>
            </p>
            
            
        {% endfor %}   
{% endblock content %}

zavrsni/travels/templates/travels/profile.html
{% extends 'travels/base.html' %}

{% block title %}
Profile
{% endblock %}

{% block content %}
    <p>{{ request.user.username}}</p>
    <p>{{ request.user.first_name }} {{ request.user.last_name}}</p>
    <p>{{ request.user.email}}</p>
            
    <h1>My images</h1>
           

    <h1>My comments</h1>
        

    <h1>My likes</h1>
          
{% endblock content %}