zavrsni/accounts/urls.py
from django.urls import path
from . import views

app_name="accounts"
urlpatterns = [
    path('dashboard', views.dashboard, name='dashboard'),
    path('profile/', views.dashboard, name="profile_login"),
    path('profile/<int:user_id>', views.profile, name="profile"),
    path('profile/rate/', views.rate, name="create-rate"),
    path("signup/", views.signup_view, name="signup"),
    path("finishup/", views.finishup, name="finishup"),
    path("dashboard/<int:travel_id>/edit", views.available, name='available'),
    path("dashboard/<int:trip_id>/edit2", views.edit2, name='edit2'),
    path("dashboard/<int:travel_id>/delete", views.delete, name='delete'),
    path('messages/', views.messages, name="messages"),
    path('messages/<int:user_id>', views.chat, name="chat"),
    path('message/<int:user_id>', views.create_message, name="create-message"),
]

zavrsni/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from travels.views import home, list, create_trip, create_travel

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
    path('travels/', include('travels.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),

    path('list/', list, name="list"),
    path('create_trip/<int:travel_id>/', create_trip, name='create_trip'),
    path('list/create/', create_travel, name="create-travel")
    
]

zavrsni/accounts/models.py
from django.db import models

# Create your models here.

zavrsni/accounts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.utils import timezone
from django.urls import reverse
from datetime import datetime
from travels.models import Travels, User, Messages, Trips, Account
from django.contrib.auth.decorators import login_required

from django.contrib.auth import login, authenticate

from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views.generic import CreateView

from django.db.models import Q

# Create your views here.
@login_required
def dashboard(request):
    user=request.user
    my_travels = Travels.objects.filter(user=request.user)
    my_messages = Messages.objects.filter(reciever_id=request.user) | Messages.objects.filter(sender_id=request.user)
    my_messages = my_messages.order_by('sent_at')

    completed_travels=Trips.objects.filter(travel__user=user, travel__status="Completed")
    ongoing_travels=Trips.objects.filter(travel__user=user, travel__status="In Progress")
    available_travels=Travels.objects.filter(user=user, status="available")

    ongoing_trip = Trips.objects.filter(traveler=user, travel__status="In Progress")
    completed_trip = Trips.objects.filter(traveler=user, travel__status="Completed")
   
    context={
        'my_travels': my_travels,   
        'my_messages': my_messages,
        'completed_travels': completed_travels,
        'ongoing_travels': ongoing_travels,
        'available_travels': available_travels,
        'ongoing_trip': ongoing_trip,
        'completed_trip': completed_trip,
    }
    return render(request, 'accounts/dashboard.html', context)

def profile(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    available_travels=Travels.objects.filter(user=user, status="available")
    
    completed_travels=Trips.objects.filter(travel__user=user, travel__status="Completed")
    ongoing_travels=Trips.objects.filter(travel__user=user, travel__status="In Progress")

    ongoing_trip = Trips.objects.filter(traveler=user, travel__status="In Progress")
    completed_trip = Trips.objects.filter(traveler=user, travel__status="Completed")
    context={
        'profile_user': user,
        'completed_travels': completed_travels,
        'ongoing_travels': ongoing_travels,
        'available_travels': available_travels,
        'ongoing_trip': ongoing_trip,
        'completed_trip': completed_trip,
    }
    return render(request, 'accounts/profile.html',context)

@login_required
def rate(request):
    
    if request.method == "POST":
        id=request.POST['trip_id']
        trip = get_object_or_404(Trips, pk=id, traveler=request.user)
        rating=int(request.POST['rate'])
        trip.rating=rating
        trip.save()
        
    return redirect(reverse('accounts:dashboard'))

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("accounts:finishup")
    template_name = "registration/signup.html"

def signup_view(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # Save the user
            user = form.save()

            # Authenticate the user
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password1")
            user = authenticate(request, username=username, password=password)

            if user is not None:
                # Log the user in
                login(request, user)
                return redirect('accounts:finishup')  # Replace 'home' with your desired redirect URL

    else:
        form = UserCreationForm()

    return render(request, "registration/signup.html", {"form": form})

def finishup(request):

    if request.method == "POST":
        
        user=request.user
       
        name = request.POST['pn']
        email = request.POST['email']
        request.user.email=email
        
        is_organization = request.POST.get('org') == 'on'

        account=Account(
            user=user,
            name=name,
            organization=is_organization
            
        )
        account.save()
        request.user.save()

        return redirect(reverse('home'))
    context = {}
    return render(request, 'accounts/finishup.html', context)

@login_required
def available(request, travel_id):
    travel=get_object_or_404(Travels, pk=travel_id)
    users=User.objects.all()
    if request.method == "POST":
        
        
        title = request.POST.get('title', '')
        desc = request.POST.get('desc', '')
        location = request.POST.get('location', '')
        date = request.POST.get('date', '')
        url = request.POST.get('url', '')
        status = request.POST.get('status', '')
        traveler1=int(request.POST['traveler'])
        if not traveler1==0:
            traveler=get_object_or_404(User, pk=traveler1)


        
        
        if not title or not desc or not location or not date or not url or not status and traveler1=="0":
            context = {
            'travel': travel,
            'users': users,
             }
            return render(request, 'accounts/edit.html', context)

        if status == 'available':
            
           
            travel.title = title
            travel.desc = desc
            travel.location = location
            travel.date = date
            travel.photo = url
            travel.status=status
            
            travel.save()

        else:

            if traveler1==0:
                context = {
                    'travel': travel,
                    'users': users,
                    }
                return render(request, 'accounts/edit.html', context)
            travel.title = title
            travel.desc = desc
            travel.location = location
            travel.date = date
            travel.photo = url
            travel.status=status
            
            travel.save()
            trip=Trips(
                travel=travel,
                traveler=traveler
            )
            trip.save()
            
        return redirect(reverse('accounts:dashboard'))
    
    
    context = {
        'travel': travel,
        'users': users,
    }
    return render(request, 'accounts/edit.html', context)


@login_required
def edit2(request, trip_id):
    trip=get_object_or_404(Trips, pk=trip_id)
    users=User.objects.all()

    if request.method == "POST":
        
        
        title = request.POST.get('title', '')
        desc = request.POST.get('desc', '')
        location = request.POST.get('location', '')
        date = request.POST.get('date', '')
        url = request.POST.get('url', '')
        status = request.POST.get('status', '')
        traveler1=int(request.POST['traveler'])
        if not traveler1==0:
            traveler=get_object_or_404(User, pk=traveler1)
    

        
        
        if not title or not desc or not location or not date or not url or not status and traveler1=="0":
            context = {
            'trip': trip,
            'users': users,
             }
            return render(request, 'accounts/edit2.html', context)

        if status == 'available':
            trip.travel.title = title
            trip.travel.desc = desc
            trip.travel.location = location
            trip.travel.date = date
            trip.travel.photo = url
            trip.travel.status=status
            
            trip.travel.save()
            trip.delete()
            

        else:

            if traveler1==0:
                context = {
                    'trip': trip,
                    'users': users,
                    }
                return render(request, 'accounts/edit2.html', context)
            trip.travel.title = title
            trip.travel.desc = desc
            trip.travel.location = location
            trip.travel.date = date
            trip.travel.photo = url
            trip.travel.status=status

            trip.travel.save()
            trip.traveler=traveler
            trip.save()
            
        return redirect(reverse('accounts:dashboard'))
    
    
    context = {
        'trip': trip,
        'users': users,
    }
    return render(request, 'accounts/edit2.html', context)


@login_required
def delete(request, travel_id):

    travel=get_object_or_404(Travels, pk=travel_id)
    travel.delete()

    return redirect(reverse('accounts:dashboard'))


@login_required
def messages(request):


    my_messages = Messages.objects.filter(reciever_id=request.user)
    mess=Messages.objects.filter(sender_id=request.user)
    
    
    seen_senders = set()
    unique_messages = []

    uni_messages = []

    for message in my_messages:
        if message.sender_id.id not in seen_senders:
            unique_messages.append(message)
            seen_senders.add(message.sender_id.id)

    for message2 in mess:
        if message2.reciever_id.id not in seen_senders:
            uni_messages.append(message2)
            seen_senders.add(message2.reciever_id.id)

    context = {
        'my_messages': unique_messages,
        'messages2': uni_messages,
    }
    return render(request, 'accounts/messages.html', context)

@login_required
def chat(request, user_id):
    
    user1 = get_object_or_404(User, pk=user_id)

    #Da imam lijevo all messages listu
    my_messages = Messages.objects.filter(reciever_id=request.user)
    mess=Messages.objects.filter(sender_id=request.user)
    
    
    seen_senders = set()
    unique_messages = []

    uni_messages = []

    for message in my_messages:

zavrsni/accounts/templates/accounts/chat.html
{% extends "accounts/messages.html" %}

{% block parent_content %}

{# Chat box #}
<p>{{user1.account.name}}</p>
<div class="messages">
            
    {% for message in chat  %}
      <div class="message 
      {% if request.user == message.sender_id %}
        my-message
        {% else %}
        their-message
      {% endif %}
        ">
        <strong>
          From:
          <a href="{% url 'accounts:profile' message.sender_id.id %}">
            {{message.sender_id.account.name}}
          </a>
        </strong> <br>
        <small>
          {{message.sent_at}}
        </small>
        <p>
          {{message.text}}
        </p>
      </div>
    {% endfor %}
      
  </div>


{# Type message #}
    
<br>
            <form method="post" action="{% url 'accounts:create-message' user_id %}">
              {% csrf_token %}
              
             <input type="text" name="message" style="width: 90%;">
              <button type="submit" style="width: 9%;"> Send</button>
          </form>
            
           


{% endblock %}

zavrsni/accounts/templates/accounts/dashboard.html
{%extends 'travels/base.html' %}


{% block content %}
<div class="content container">
    <div class="row">
        <div class="col-md-9">
          <h1>Hello {{user.account.name }}</h1>
          <p>Email: {{user.email}}</p>
       
          {% if user.account.organization %} 

      <div class="row">
        <div class="col-md-12">
          <h1>Available Travels</h1>
          {% if available_travels %}

          {% for travel in available_travels  %}
          <div class="travel">
            <h3>{{travel.title}}</h3>
            <img src="{{travel.photo}}" style="width: 300px;">
            <p>{{travel.desc}}</p>
            <p><strong>City:</strong>  {{travel.location}}</p>
            <p><strong>Date of travel:</strong> {{travel.date}}</p>
            <p><strong>Status: </strong>{{travel.status}}</p>
            <p>     
              <a class="btn btn-primary" href="{% url 'accounts:available' travel.id %}">Edit</a>
              <a class="btn btn-primary" href="{% url 'accounts:delete' travel.id %}">Delete</a>
            </p>
        </div>
          {% endfor %}

          {% else %}
            <p>None at this time</p>
          {% endif %} {# end if for if available travels exist #}

        </div>
      </div>
        
       
      <div class="row">
        <div class="col-md-12">
          <h1>Ongoing Travels</h1>
          {% if ongoing_travels %}

          {% for place in ongoing_travels  %}
          <div class="travel">
            <h3>{{place.travel.title}}</h3>
            <img src="{{place.travel.photo}}" style="width: 300px;">
            <p>{{place.travel.desc}}</p>
            <p><strong>City:</strong>  {{place.travel.location}}</p>
            <p><strong>Date of travel:</strong> {{place.travel.date}}</p>
            <p><strong>Status: </strong>{{place.travel.status}}</p>
            <p>
              <strong>Traveler: </strong><a href="{% url 'accounts:profile' place.traveler.id%}">{{place.traveler.account.name}}</a>
              <a class="btn btn-primary" href="{% url 'accounts:chat' place.traveler.id%}">Message</a>
            </p>
            <p>     
              <a class="btn btn-primary" href="{% url 'accounts:edit2' place.id %}">Edit</a>
              <a class="btn btn-primary" href="{% url 'accounts:delete' place.travel.id %}">Delete</a>
            </p>
            
            <p>
              
            </p>
        </div>
          {% endfor %}

          {% else %}
            <p>None at this time</p>
          {% endif %} {# end if for if ongoing travels exist #}

        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <h1>Completed Travels</h1>
          {% if completed_travels %}

          {% for place in completed_travels  %}
          <div class="travel">
            <h3>{{place.travel.title}}</h3>
            <img src="{{place.travel.photo}}" style="width: 300px;">
            <p>{{place.travel.desc}}</p>
            <p><strong>City:</strong>  {{place.travel.location}}</p>
            <p><strong>Date of travel:</strong> {{place.travel.date}}</p>
            <p><strong>Status: </strong>{{place.travel.status}}</p>
            <p>
              <strong>Traveler: </strong><a href="{% url 'accounts:profile' place.traveler.id%}">{{place.traveler.account.name}}</a>
              <a class="btn btn-primary" href="{% url 'accounts:chat' place.traveler.id%}">Message</a>
            </p>
          <p><strong>Rating: </strong> {{place.rating}}</p>
          <p>
            <a class="btn btn-primary" href="{% url 'accounts:delete' place.travel.id %}">Delete</a>
          </p>
        </div>
          {% endfor %}

          {% else %}
            <p>None at this time</p>
          {% endif %} {# end if ffor if completed travels exist #}
        </div>
      </div>




      {% else %} {# else for if user isnt organization #}

      <div class="row">
        <div class="col-md-12">
          <h1>Ongoing trips</h1>
          {% if ongoing_trip %}

          {% for trip in ongoing_trip  %}
          <div class="trip">
            <h3>{{trip.travel.title}}</h3>
            <p>
              <strong>Organization: </strong><a href="{% url 'accounts:profile' trip.travel.user.id%}">{{trip.travel.user.account.name}}</a>
              <a class="btn btn-primary" href="{% url 'accounts:chat' trip.travel.user.id%}">Message</a>
            </p>
            <img src="{{trip.travel.photo}}" style="width: 300px;">
            <p>{{trip.travel.desc}}</p>
            <p><strong>City:</strong>  {{trip.travel.location}}</p>
            <p><strong>Date of travel:</strong> {{trip.travel.date}}</p>
            <p><strong>Status: </strong>{{trip.travel.status}}</p>
        </div>
          {% endfor %}

          {% else %}
            <p>None at this time</p>
          {% endif %} {# end if ffor if ongoing trips exist #}
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <h1>Completed trips</h1>
          {% if completed_trip %}

          {% for trip in completed_trip  %}
          <div class="trip">
            <h3>{{trip.travel.title}}</h3>
            
            <p>
              <strong>Organization: </strong><a href="{% url 'accounts:profile' trip.travel.user.id%}">{{trip.travel.user.account.name}}</a>
              <a class="btn btn-primary" href="{% url 'accounts:chat' trip.travel.user.id%}">Message</a>
            </p>
            <img src="{{trip.travel.photo}}" style="width: 300px;">
            <p>{{trip.travel.desc}}</p>
            <p><strong>City:</strong>  {{trip.travel.location}}</p>
            <p><strong>Date of travel:</strong> {{trip.travel.date}}</p>
            <p><strong>Status: </strong>{{trip.travel.status}}</p>

            
            {% if trip.rating == 0 %}
            <form method="post" action="{% url 'accounts:create-rate' %}">
              {% csrf_token %}
              <input type="hidden" name="trip_id" value="{{ trip.id }}">
              <label>Rate: </label>
               <select name="rate" id="rate">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
               </select>
              <button type="submit"> Rate</button>
          </form>
            {% else %}

            <p><strong>Rating: </strong> {{trip.rating}}</p>
            {% endif %}
              

        </div>
          {% endfor %}

          {% else %}
            <p>None at this time</p>
          {% endif %} {# end if ffor if completed trips exist #}
        </div>
      </div>

      {% endif %} {# end if for is user organization #}
            
        </div>
        <div class="col-md-3">
          <h1>Messages</h1>
           <a href="{% url 'accounts:messages' %}">all messages</a>
          <div class="messages">
            
            {% for message in my_messages  %}
              <div class="message 
              {% if request.user == message.sender_id %}
                my-message
                {% else %}
                their-message
              {% endif %}
                ">
                <strong>
                  From:
                  <a href="{% url 'accounts:profile' message.sender_id.id %}">
                    {{message.sender_id.account.name}}
                  </a>
                </strong> <br>
                <small>
                  {{message.sent_at}}
                </small>
                <p>
                  {{message.text}}
                </p>
              </div>
            {% endfor %}
              
          </div>
        </div>


      </div>

  </div>
{% endblock content %}
    

zavrsni/accounts/templates/accounts/edit.html

{% extends 'travels/base.html' %}

{% block title %}
Edit travel
{% endblock %}

{% block content %}
        <h1>Edit</h1>
        <form method="post" action="{% url 'accounts:available' travel.id %}">
            {% csrf_token %}
            <input type="hidden" name="travel_id" value="{{ travel.id }}">
            
            <label>Title</label>
            <input type="text" name="title" value="{{travel.title}}">
            <br>
        
            <label>Description</label>
            <input type="text" name="desc" value="{{travel.desc}}">
            <br>
            
            <label>Location</label>
            <input type="text" name="location" value="{{travel.location}}">
            <br>
        
            <label>Date</label>
            <input type="date" name="date" value="{{ travel.date|date:'Y-m-d' }}"">
            <br>
            
            <label>Photo url</label>
            <input type="text" name="url" value="{{travel.photo}}">
            <br>

            <label>Status </label>
            <select name="status" id="status">
                <option value="available" {% if travel.status == "available" %}selected{% endif %}>available</option>
                <option value="In Progress" {% if travel.status == "In Progress" %}selected{% endif %}>In Progress</option>
                <option value="Completed" {% if travel.status == "Completed" %}selected{% endif %}>Completed</option>
            </select>
            <br>

            <label>Traveler</label>
            <select name="traveler" id="traveler">
                <option value="0">-- Select a Traveler --</option>
                {% for user in users %}
                    <option value="{{ user.id }}">{{ user.account.name }}</option>
                {% endfor %}
            </select>
            <br>
        
            <button type="submit"> Change </button>
        </form>
        
{% endblock content %}

zavrsni/accounts/templates/accounts/edit2.html

{% extends 'travels/base.html' %}

{% block title %}
Edit travel
{% endblock %}

{% block content %}
        <h1>Edit</h1>
        <form method="post" action="{% url 'accounts:edit2' trip.id %}">
            {% csrf_token %}
            <input type="hidden" name="travel_id" value="{{ trip.travel.id }}">
            
            <label>Title</label>
            <input type="text" name="title" value="{{trip.travel.title}}">
            <br>
        
            <label>Description</label>
            <input type="text" name="desc" value="{{trip.travel.desc}}">
            <br>
            
            <label>Location</label>
            <input type="text" name="location" value="{{trip.travel.location}}">
            <br>
        
            <label>Date</label>
            <input type="date" name="date" value="{{ trip.travel.date|date:'Y-m-d' }}"">
            <br>
            
            <label>Photo url</label>
            <input type="text" name="url" value="{{trip.travel.photo}}">
            <br>

            <label>Status </label>
            <select name="status" id="status">
                <option value="available" {% if trip.travel.status == "available" %}selected{% endif %}>available</option>
                <option value="In Progress" {% if trip.travel.status == "In Progress" %}selected{% endif %}>In Progress</option>
                <option value="Completed" {% if trip.travel.status == "Completed" %}selected{% endif %}>Completed</option>
            </select>
            <br>

            <label>Traveler</label>
            <select name="traveler" id="traveler">
                <option value="0">-- Select a Traveler --</option>
                {% for user in users %}
                    <option value="{{ user.id }}" 
                        {% if user.account.name == trip.traveler.account.name %}selected{% endif %}>
                        {{ user.account.name }}
                    </option>
                {% endfor %}
            </select>
            <br>
            
            <button type="submit"> Change </button>
        </form>
        
{% endblock content %}

zavrsni/accounts/templates/accounts/messages.html
{% extends "travels/base.html" %}

{% block content %}


<div class="content container">
    <div class="row">
        <div class="col-md-3" style="border-right: 2px solid black;">
            <h1>All Messages</h1>
            

            
            {% for message in my_messages  %}

            <div class="messages">
                <a href="{% url 'accounts:chat' message.sender_id.id%}">{{message.sender_id.account.name}}</a>
                
            </div>
                
            {% endfor %}

            {% for message in messages2  %}

            <div class="messages">
                <a href="{% url 'accounts:chat' message.reciever_id.id%}">{{message.reciever_id.account.name}}</a>
                
            </div>
                
            {% endfor %}

        </div>

        <div class="col-md-9">
            <h1>Message box</h1>
            {% block parent_content %}

            <p>Open the chat</p>

            {% endblock %}
        </div>
        
        
    </div>
</div>



    

{% endblock %}

zavrsni/accounts/templates/accounts/profile.html
{%extends 'travels/base.html' %}


{% block content %}
<div class="content container">
    <div class="row">
        <div class="col-md-12">
          <h1> {{profile_user.account.name }}'s profile page</h1>
          <p>Email: {{profile_user.email}}</p>
        </div>
      </div>
      {% if profile_user.account.organization %} 

      <div class="row">
        <div class="col-md-12">
          <h1>Available Travels</h1>
          {% if available_travels %}

          {% for travel in available_travels  %}
          <div class="travel">
            <h3>{{travel.title}}</h3>
            <img src="{{travel.photo}}" style="width: 300px;">
            <p>{{travel.desc}}</p>
            <p><strong>City:</strong>  {{travel.location}}</p>
            <p><strong>Date of travel:</strong> {{travel.date}}</p>
            <p><strong>Status: </strong>{{travel.status}}</p>
        </div>
          {% endfor %}

          {% else %}
            <p>None at this time</p>
          {% endif %} {# end if for if available travels exist #}

        </div>
      </div>
        
       
      <div class="row">
        <div class="col-md-12">
          <h1>Ongoing Travels</h1>
          {% if ongoing_travels %}

          {% for place in ongoing_travels  %}
          <div class="travel">
            <h3>{{place.travel.title}}</h3>
            <img src="{{place.travel.photo}}" style="width: 300px;">
            <p>{{place.travel.desc}}</p>
            <p><strong>City:</strong>  {{place.travel.location}}</p>
            <p><strong>Date of travel:</strong> {{place.travel.date}}</p>
            <p><strong>Status: </strong>{{place.travel.status}}</p>
            <p>
              <strong>Traveler: </strong><a href="{% url 'accounts:profile' place.traveler.id%}">{{place.traveler.account.name}}</a>
              <a class="btn btn-primary" href="{% url 'accounts:chat' place.traveler.id%}">Message</a>
            </p>
            
        </div>
          {% endfor %}

          {% else %}
            <p>None at this time</p>
          {% endif %} {# end if for if ongoing travels exist #}

        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <h1>Completed Travels</h1>
          {% if completed_travels %}

          {% for place in completed_travels  %}
          <div class="travel">
            <h3>{{place.travel.title}}</h3>
            <img src="{{place.travel.photo}}" style="width: 300px;">
            <p>{{place.travel.desc}}</p>
            <p><strong>City:</strong>  {{place.travel.location}}</p>
            <p><strong>Date of travel:</strong> {{place.travel.date}}</p>
            <p><strong>Status: </strong>{{place.travel.status}}</p>
            <p>
              <strong>Traveler: </strong><a href="{% url 'accounts:profile' place.traveler.id%}">{{place.traveler.account.name}}</a>
              <a class="btn btn-primary" href="{% url 'accounts:chat' place.traveler.id%}">Message</a>
            </p>
            <p><strong>Rating: </strong> {{place.rating}}</p>
        </div>
          {% endfor %}

          {% else %}
            <p>None at this time</p>
          {% endif %} {# end if ffor if completed travels exist #}
        </div>
      </div>


      {% else %} {# else for if user isnt organization #}

      <div class="row">
        <div class="col-md-12">
          <h1>Ongoing trips</h1>
          {% if ongoing_trip %}

          {% for trip in ongoing_trip  %}
          <div class="trip">
            <h3>{{trip.travel.title}}</h3>
            <p>
              <strong>Organization: </strong><a href="{% url 'accounts:profile' trip.travel.user.id%}">{{trip.travel.user.account.name}}</a>
              <a class="btn btn-primary" href="{% url 'accounts:chat' trip.travel.user.id%}">Message</a>
            </p>
            <img src="{{trip.travel.photo}}" style="width: 300px;">
            <p>{{trip.travel.desc}}</p>
            <p><strong>City:</strong>  {{trip.travel.location}}</p>
            <p><strong>Date of travel:</strong> {{trip.travel.date}}</p>
            <p><strong>Status: </strong>{{trip.travel.status}}</p>
        </div>
          {% endfor %}

          {% else %}
            <p>None at this time</p>
          {% endif %} {# end if ffor if ongoing trips exist #}
        </div>
      </div>

      <div class="row">
        <div class="col-md-12">
          <h1>Completed trips</h1>
          {% if completed_trip %}

          {% for trip in completed_trip  %}
          <div class="trip">
            <h3>{{trip.travel.title}}</h3>
            
            <p>
              <strong>Organization: </strong><a href="{% url 'accounts:profile' trip.travel.user.id%}">{{trip.travel.user.account.name}}</a>
              <a class="btn btn-primary" href="{% url 'accounts:chat' trip.travel.user.id%}">Message</a>
            </p>
            <img src="{{trip.travel.photo}}" style="width: 300px;">
            <p>{{trip.travel.desc}}</p>
            <p><strong>City:</strong>  {{trip.travel.location}}</p>
            <p><strong>Date of travel:</strong> {{trip.travel.date}}</p>
            <p><strong>Status: </strong>{{trip.travel.status}}</p>
        </div>
          {% endfor %}

          {% else %}
            <p>None at this time</p>
          {% endif %} {# end if ffor if ongoing trips exist #}
        </div>
      </div>

      {% endif %} {# end if for is user organization #}
  </div>
{% endblock content %}
    